# Create a 3x3x3 array with random values

In [1]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.0941493  0.64526376 0.61695865]
  [0.73650711 0.78899546 0.41999877]
  [0.24391638 0.79372133 0.24949706]]

 [[0.55510875 0.69216911 0.76499818]
  [0.8846343  0.47701677 0.94972769]
  [0.56038648 0.72164833 0.35809495]]

 [[0.41593523 0.42431983 0.86477755]
  [0.58502128 0.9413661  0.16284163]
  [0.65646477 0.9652593  0.63937675]]]


# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
import numpy as np
x = np.diag(1+np.arange(4), k = -1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
import numpy as np
x = np.ones((3,3))
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Normalize a 5x5 random matrix

In [4]:
import numpy as np
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.20948867 0.80443937 0.85052666 0.62394191 0.14279475]
 [0.10944632 0.53847733 0.32546452 0.76664573 0.05560182]
 [0.87199884 0.7182952  0.78496799 0.37414633 0.66119711]
 [0.66147203 0.6016134  0.40576556 0.14372988 0.46531181]
 [0.65712843 0.43459521 0.76276193 0.80397916 0.64608691]]
After normalization:
[[0.18849512 0.9172468  0.97369885 0.6961565  0.10680212]
 [0.06595382 0.59147143 0.33055326 0.87095358 0.        ]
 [1.         0.8117293  0.89339642 0.39018333 0.74179018]
 [0.74212692 0.66880643 0.42891355 0.10794756 0.5018514 ]
 [0.73680648 0.46422681 0.86619634 0.91668308 0.72328178]]


# How to find common values between two arrays?

In [5]:
import numpy as np
array1 = np.array([1, 2, 3 , 4, 5, 6])
print("Array1: ",array1)
array2 = [10, 9, 8, 7, 6, 5]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [1 2 3 4 5 6]
Array2:  [10, 9, 8, 7, 6, 5]
Common values between two arrays:
[5 6]


# How to get the dates of yesterday, today and tomorrow?

In [7]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


# Consider two random array A and B, check if they are equal

In [8]:

import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[1 0 1 1 1 0]
Second array:
[0 1 0 0 0 1]
Test above two arrays are equal or not!
False


# Create random vector of size 10 and replace the maximum value by 0 

In [9]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0 : ")
print(x)

Original array:
[0.97180729 0.86656045 0.50479467 0.25111951 0.851529   0.28559383
 0.64504351 0.74122313 0.50241734 0.53735804]
Maximum value replaced by 0 : 
[0.         0.86656045 0.50479467 0.25111951 0.851529   0.28559383
 0.64504351 0.74122313 0.50241734 0.53735804]


# How to print all the values of an array?

In [10]:
import numpy as np
array = np.arange(20)
np. set_printoptions(threshold=np.inf)
print("All values of an array")
print(array)

All values of an array
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


# Subtract the mean of each row of a matrix

In [11]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(3, 6)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.60924419 0.64672835 0.21376755 0.8181115  0.2789411  0.66681648]
 [0.36519127 0.30662354 0.41358439 0.57402723 0.90864835 0.29084921]
 [0.13838879 0.31898371 0.67013081 0.59015463 0.98122616 0.21795963]]

Subtract the mean of each row of the said matrix:

[[ 0.07030933  0.10779349 -0.32516731  0.27917664 -0.25999376  0.12788162]
 [-0.11129607 -0.16986379 -0.06290294  0.0975399   0.43216102 -0.18563812]
 [-0.34775183 -0.16715691  0.18399019  0.10401401  0.49508554 -0.26818099]]


# Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [12]:
import numpy as np
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[5. 4. 3. 2. 4. 4. 1. 3. 3. 1.]


# How to get the diagonal of a dot product?

In [13]:
import numpy as np
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([0.74975584, 1.32418311, 1.12505983, 0.36374869, 0.99929196])

# How to find the most frequent value in an array?

In [14]:
import numpy as np
x = np.random.randint(0, 3, 6)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[2 2 2 1 0 2]
Most frequent value in the above array:
2


# How to get the n largest values of an array

In [15]:
import numpy as np
x = np.arange(15)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[14]


# How to create a record array from a regular array?

In [16]:
import numpy as np
arra1 = np.array([("Teddy", 88.5, 90), ("Adi", 87.5, 99), ("Ritti", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T, names='col1, col2, col3', formats = 'S80, f8, i8')
print(result)

Original arrays:
[['Teddy' '88.5' '90']
 ['Adi' '87.5' '99']
 ['Ritti' '85.5' '91']]

Record array;
[(b'Teddy', 88.5, 90) (b'Adi', 87.5, 99) (b'Ritti', 85.5, 91)]
